# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from httpbin_python_sdk.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    ABSOLUTEREDIRECT_N = "/absolute-redirect/{n}"
    ANYTHING = "/anything"
    ANYTHING_ANYTHING = "/anything/{anything}"
    BASE64_VALUE = "/base64/{value}"
    BASICAUTH_USER_PASSWD = "/basic-auth/{user}/{passwd}"
    BEARER = "/bearer"
    BROTLI = "/brotli"
    BYTES_N = "/bytes/{n}"
    CACHE = "/cache"
    CACHE_VALUE = "/cache/{value}"
    COOKIES = "/cookies"
    COOKIES_DELETE = "/cookies/delete"
    COOKIES_SET = "/cookies/set"
    COOKIES_SET_NAME_VALUE = "/cookies/set/{name}/{value}"
    DEFLATE = "/deflate"
    DELAY_DELAY = "/delay/{delay}"
    DELETE = "/delete"
    DENY = "/deny"
    DIGESTAUTH_QOP_USER_PASSWD = "/digest-auth/{qop}/{user}/{passwd}"
    DIGESTAUTH_QOP_USER_PASSWD_ALGORITHM = "/digest-auth/{qop}/{user}/{passwd}/{algorithm}"
    DIGESTAUTH_QOP_USER_PASSWD_ALGORITHM_STALE_AFTER = "/digest-auth/{qop}/{user}/{passwd}/{algorithm}/{stale_after}"
    DRIP = "/drip"
    ENCODING_UTF8 = "/encoding/utf8"
    ETAG_ETAG = "/etag/{etag}"
    GET = "/get"
    GZIP = "/gzip"
    HEADERS = "/headers"
    HIDDENBASICAUTH_USER_PASSWD = "/hidden-basic-auth/{user}/{passwd}"
    HTML = "/html"
    IMAGE = "/image"
    IMAGE_JPEG = "/image/jpeg"
    IMAGE_PNG = "/image/png"
    IMAGE_SVG = "/image/svg"
    IMAGE_WEBP = "/image/webp"
    IP = "/ip"
    JSON = "/json"
    LINKS_N_OFFSET = "/links/{n}/{offset}"
    PATCH = "/patch"
    POST = "/post"
    PUT = "/put"
    RANGE_NUMBYTES = "/range/{numbytes}"
    REDIRECTTO = "/redirect-to"
    REDIRECT_N = "/redirect/{n}"
    RELATIVEREDIRECT_N = "/relative-redirect/{n}"
    RESPONSEHEADERS = "/response-headers"
    ROBOTS_TXT = "/robots.txt"
    STATUS_CODES = "/status/{codes}"
    STREAMBYTES_N = "/stream-bytes/{n}"
    STREAM_N = "/stream/{n}"
    USERAGENT = "/user-agent"
    UUID = "/uuid"
    XML = "/xml"
