# coding: utf-8

"""
    httpbin.org

    A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>

    The version of the OpenAPI document: 0.9.2
    Contact: me@kennethreitz.org
    Created by: https://kennethreitz.org
"""

from httpbin_python_sdk.paths.anything_anything.delete import GetAnythingRaw
from httpbin_python_sdk.paths.anything.get import GetDataRaw
from httpbin_python_sdk.paths.anything.delete import GetData0Raw
from httpbin_python_sdk.paths.anything.patch import GetData1Raw
from httpbin_python_sdk.paths.anything_anything.get import GetData2Raw
from httpbin_python_sdk.paths.anything.trace import GetPassedDataRaw
from httpbin_python_sdk.paths.anything_anything.trace import GetPassedData0Raw
from httpbin_python_sdk.paths.anything.post import PostRequestDataRaw
from httpbin_python_sdk.paths.anything.put import PutRequestDataRaw
from httpbin_python_sdk.paths.anything_anything.put import ReturnDataRaw
from httpbin_python_sdk.paths.anything_anything.post import ReturnRequestDataRaw
from httpbin_python_sdk.paths.anything_anything.patch import UpdateAnythingDataRaw


class AnythingApiRaw(
    GetAnythingRaw,
    GetDataRaw,
    GetData0Raw,
    GetData1Raw,
    GetData2Raw,
    GetPassedDataRaw,
    GetPassedData0Raw,
    PostRequestDataRaw,
    PutRequestDataRaw,
    ReturnDataRaw,
    ReturnRequestDataRaw,
    UpdateAnythingDataRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
