# coding: utf-8

"""
    httpbin.org

    A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>

    The version of the OpenAPI document: 0.9.2
    Contact: me@kennethreitz.org
    Created by: https://kennethreitz.org
"""

from httpbin_python_sdk.paths.anything_anything.delete import GetAnything
from httpbin_python_sdk.paths.anything.get import GetData
from httpbin_python_sdk.paths.anything.delete import GetData0
from httpbin_python_sdk.paths.anything.patch import GetData1
from httpbin_python_sdk.paths.anything_anything.get import GetData2
from httpbin_python_sdk.paths.anything.trace import GetPassedData
from httpbin_python_sdk.paths.anything_anything.trace import GetPassedData0
from httpbin_python_sdk.paths.anything.post import PostRequestData
from httpbin_python_sdk.paths.anything.put import PutRequestData
from httpbin_python_sdk.paths.anything_anything.put import ReturnData
from httpbin_python_sdk.paths.anything_anything.post import ReturnRequestData
from httpbin_python_sdk.paths.anything_anything.patch import UpdateAnythingData
from httpbin_python_sdk.apis.tags.anything_api_raw import AnythingApiRaw


class AnythingApi(
    GetAnything,
    GetData,
    GetData0,
    GetData1,
    GetData2,
    GetPassedData,
    GetPassedData0,
    PostRequestData,
    PutRequestData,
    ReturnData,
    ReturnRequestData,
    UpdateAnythingData,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AnythingApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AnythingApiRaw(api_client)
