# coding: utf-8

"""
    httpbin.org

    A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>

    The version of the OpenAPI document: 0.9.2
    Contact: me@kennethreitz.org
    Created by: https://kennethreitz.org
"""

from httpbin_python_sdk.paths.digest_auth_qop_user_passwd.get import DigestAuthPromptRaw
from httpbin_python_sdk.paths.bearer.get import PromptAuthorizationRaw
from httpbin_python_sdk.paths.digest_auth_qop_user_passwd_algorithm_stale_after.get import PromptAuthorizationUsingDigestRaw
from httpbin_python_sdk.paths.basic_auth_user_passwd.get import PromptAuthorizationUsingHttpGetRaw
from httpbin_python_sdk.paths.hidden_basic_auth_user_passwd.get import PromptUserAuthorizationRaw
from httpbin_python_sdk.paths.digest_auth_qop_user_passwd_algorithm.get import UserAuthorizationDigestRaw


class AuthApiRaw(
    DigestAuthPromptRaw,
    PromptAuthorizationRaw,
    PromptAuthorizationUsingDigestRaw,
    PromptAuthorizationUsingHttpGetRaw,
    PromptUserAuthorizationRaw,
    UserAuthorizationDigestRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
