# coding: utf-8

"""
    httpbin.org

    A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>

    The version of the OpenAPI document: 0.9.2
    Contact: me@kennethreitz.org
    Created by: https://kennethreitz.org
"""

from httpbin_python_sdk.paths.digest_auth_qop_user_passwd.get import DigestAuthPrompt
from httpbin_python_sdk.paths.bearer.get import PromptAuthorization
from httpbin_python_sdk.paths.digest_auth_qop_user_passwd_algorithm_stale_after.get import PromptAuthorizationUsingDigest
from httpbin_python_sdk.paths.basic_auth_user_passwd.get import PromptAuthorizationUsingHttpGet
from httpbin_python_sdk.paths.hidden_basic_auth_user_passwd.get import PromptUserAuthorization
from httpbin_python_sdk.paths.digest_auth_qop_user_passwd_algorithm.get import UserAuthorizationDigest
from httpbin_python_sdk.apis.tags.auth_api_raw import AuthApiRaw


class AuthApi(
    DigestAuthPrompt,
    PromptAuthorization,
    PromptAuthorizationUsingDigest,
    PromptAuthorizationUsingHttpGet,
    PromptUserAuthorization,
    UserAuthorizationDigest,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AuthApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AuthApiRaw(api_client)
