# coding: utf-8

"""
    httpbin.org

    A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>

    The version of the OpenAPI document: 0.9.2
    Contact: me@kennethreitz.org
    Created by: https://kennethreitz.org
"""

from httpbin_python_sdk.paths.cookies_delete.get import DeleteRedirectToCookieListRaw
from httpbin_python_sdk.paths.cookies.get import GetDataRaw
from httpbin_python_sdk.paths.cookies_set_name_value.get import SetCookieRedirectRaw
from httpbin_python_sdk.paths.cookies_set.get import SetRedirectRaw


class CookiesApiRaw(
    DeleteRedirectToCookieListRaw,
    GetDataRaw,
    SetCookieRedirectRaw,
    SetRedirectRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
