# coding: utf-8

"""
    httpbin.org

    A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>

    The version of the OpenAPI document: 0.9.2
    Contact: me@kennethreitz.org
    Created by: https://kennethreitz.org
"""

from httpbin_python_sdk.paths.cookies_delete.get import DeleteRedirectToCookieList
from httpbin_python_sdk.paths.cookies.get import GetData
from httpbin_python_sdk.paths.cookies_set_name_value.get import SetCookieRedirect
from httpbin_python_sdk.paths.cookies_set.get import SetRedirect
from httpbin_python_sdk.apis.tags.cookies_api_raw import CookiesApiRaw


class CookiesApi(
    DeleteRedirectToCookieList,
    GetData,
    SetCookieRedirect,
    SetRedirect,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CookiesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CookiesApiRaw(api_client)
