# coding: utf-8

"""
    httpbin.org

    A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>

    The version of the OpenAPI document: 0.9.2
    Contact: me@kennethreitz.org
    Created by: https://kennethreitz.org
"""

from httpbin_python_sdk.paths.base64_value.get import DecodeBase64urlStringRaw
from httpbin_python_sdk.paths.delay_delay.delete import DelayedResponseDeleteRaw
from httpbin_python_sdk.paths.delay_delay.get import DelayedResponseGetRaw
from httpbin_python_sdk.paths.drip.get import DripDataOverDurationRaw
from httpbin_python_sdk.paths.links_n_offset.get import GeneratePageContainingLinksRaw
from httpbin_python_sdk.paths.uuid.get import GenerateUuidRaw
from httpbin_python_sdk.paths.bytes_n.get import GetRandomBytesRaw
from httpbin_python_sdk.paths.delay_delay.put import ReturnDelayedResponseRaw
from httpbin_python_sdk.paths.delay_delay.post import ReturnDelayedResponse0Raw
from httpbin_python_sdk.paths.delay_delay.patch import ReturnDelayedResponse1Raw
from httpbin_python_sdk.paths.delay_delay.trace import ReturnDelayedResponseTraceRaw
from httpbin_python_sdk.paths.stream_n.get import StreamJsonResponsesRaw
from httpbin_python_sdk.paths.range_numbytes.get import StreamRandomBytesRaw
from httpbin_python_sdk.paths.stream_bytes_n.get import StreamRandomBytes0Raw


class DynamicDataApiRaw(
    DecodeBase64urlStringRaw,
    DelayedResponseDeleteRaw,
    DelayedResponseGetRaw,
    DripDataOverDurationRaw,
    GeneratePageContainingLinksRaw,
    GenerateUuidRaw,
    GetRandomBytesRaw,
    ReturnDelayedResponseRaw,
    ReturnDelayedResponse0Raw,
    ReturnDelayedResponse1Raw,
    ReturnDelayedResponseTraceRaw,
    StreamJsonResponsesRaw,
    StreamRandomBytesRaw,
    StreamRandomBytes0Raw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
