# coding: utf-8

"""
    httpbin.org

    A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>

    The version of the OpenAPI document: 0.9.2
    Contact: me@kennethreitz.org
    Created by: https://kennethreitz.org
"""

from httpbin_python_sdk.paths.base64_value.get import DecodeBase64urlString
from httpbin_python_sdk.paths.delay_delay.delete import DelayedResponseDelete
from httpbin_python_sdk.paths.delay_delay.get import DelayedResponseGet
from httpbin_python_sdk.paths.drip.get import DripDataOverDuration
from httpbin_python_sdk.paths.links_n_offset.get import GeneratePageContainingLinks
from httpbin_python_sdk.paths.uuid.get import GenerateUuid
from httpbin_python_sdk.paths.bytes_n.get import GetRandomBytes
from httpbin_python_sdk.paths.delay_delay.put import ReturnDelayedResponse
from httpbin_python_sdk.paths.delay_delay.post import ReturnDelayedResponse0
from httpbin_python_sdk.paths.delay_delay.patch import ReturnDelayedResponse1
from httpbin_python_sdk.paths.delay_delay.trace import ReturnDelayedResponseTrace
from httpbin_python_sdk.paths.stream_n.get import StreamJsonResponses
from httpbin_python_sdk.paths.range_numbytes.get import StreamRandomBytes
from httpbin_python_sdk.paths.stream_bytes_n.get import StreamRandomBytes0
from httpbin_python_sdk.apis.tags.dynamic_data_api_raw import DynamicDataApiRaw


class DynamicDataApi(
    DecodeBase64urlString,
    DelayedResponseDelete,
    DelayedResponseGet,
    DripDataOverDuration,
    GeneratePageContainingLinks,
    GenerateUuid,
    GetRandomBytes,
    ReturnDelayedResponse,
    ReturnDelayedResponse0,
    ReturnDelayedResponse1,
    ReturnDelayedResponseTrace,
    StreamJsonResponses,
    StreamRandomBytes,
    StreamRandomBytes0,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: DynamicDataApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = DynamicDataApiRaw(api_client)
