# coding: utf-8

"""
    httpbin.org

    A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>

    The version of the OpenAPI document: 0.9.2
    Contact: me@kennethreitz.org
    Created by: https://kennethreitz.org
"""

from httpbin_python_sdk.paths.delete.delete import DeleteRequestParameters
from httpbin_python_sdk.paths.post.post import PostRequestParameters
from httpbin_python_sdk.paths.put.put import PutRequestParameters
from httpbin_python_sdk.paths.get.get import RequestQueryParametersGet
from httpbin_python_sdk.paths.patch.patch import UpdateRequestParameters
from httpbin_python_sdk.apis.tags.http_methods_api_raw import HTTPMethodsApiRaw


class HTTPMethodsApi(
    DeleteRequestParameters,
    PostRequestParameters,
    PutRequestParameters,
    RequestQueryParametersGet,
    UpdateRequestParameters,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: HTTPMethodsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = HTTPMethodsApiRaw(api_client)
