# coding: utf-8

"""
    httpbin.org

    A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>

    The version of the OpenAPI document: 0.9.2
    Contact: me@kennethreitz.org
    Created by: https://kennethreitz.org
"""

from httpbin_python_sdk.paths.delete.delete import DeleteRequestParametersRaw
from httpbin_python_sdk.paths.post.post import PostRequestParametersRaw
from httpbin_python_sdk.paths.put.put import PutRequestParametersRaw
from httpbin_python_sdk.paths.get.get import RequestQueryParametersGetRaw
from httpbin_python_sdk.paths.patch.patch import UpdateRequestParametersRaw


class HTTPMethodsApiRaw(
    DeleteRequestParametersRaw,
    PostRequestParametersRaw,
    PutRequestParametersRaw,
    RequestQueryParametersGetRaw,
    UpdateRequestParametersRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
