# coding: utf-8

"""
    httpbin.org

    A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>

    The version of the OpenAPI document: 0.9.2
    Contact: me@kennethreitz.org
    Created by: https://kennethreitz.org
"""

from httpbin_python_sdk.paths.image.get import GetByAcceptHeader
from httpbin_python_sdk.paths.image_jpeg.get import GetJpegImage
from httpbin_python_sdk.paths.image_png.get import GetPngImage
from httpbin_python_sdk.paths.image_svg.get import GetSvgImage
from httpbin_python_sdk.paths.image_webp.get import GetWebpImage
from httpbin_python_sdk.apis.tags.images_api_raw import ImagesApiRaw


class ImagesApi(
    GetByAcceptHeader,
    GetJpegImage,
    GetPngImage,
    GetSvgImage,
    GetWebpImage,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ImagesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ImagesApiRaw(api_client)
