# coding: utf-8

"""
    httpbin.org

    A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>

    The version of the OpenAPI document: 0.9.2
    Contact: me@kennethreitz.org
    Created by: https://kennethreitz.org
"""

from httpbin_python_sdk.paths.image.get import GetByAcceptHeaderRaw
from httpbin_python_sdk.paths.image_jpeg.get import GetJpegImageRaw
from httpbin_python_sdk.paths.image_png.get import GetPngImageRaw
from httpbin_python_sdk.paths.image_svg.get import GetSvgImageRaw
from httpbin_python_sdk.paths.image_webp.get import GetWebpImageRaw


class ImagesApiRaw(
    GetByAcceptHeaderRaw,
    GetJpegImageRaw,
    GetPngImageRaw,
    GetSvgImageRaw,
    GetWebpImageRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
