# coding: utf-8

"""
    httpbin.org

    A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>

    The version of the OpenAPI document: 0.9.2
    Contact: me@kennethreitz.org
    Created by: https://kennethreitz.org
"""

from httpbin_python_sdk.paths.headers.get import IncomingHeadersGetRaw
from httpbin_python_sdk.paths.ip.get import IpAddressGetRaw
from httpbin_python_sdk.paths.user_agent.get import UserAgentGetRaw


class RequestInspectionApiRaw(
    IncomingHeadersGetRaw,
    IpAddressGetRaw,
    UserAgentGetRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
