# coding: utf-8

"""
    httpbin.org

    A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>

    The version of the OpenAPI document: 0.9.2
    Contact: me@kennethreitz.org
    Created by: https://kennethreitz.org
"""

from httpbin_python_sdk.paths.headers.get import IncomingHeadersGet
from httpbin_python_sdk.paths.ip.get import IpAddressGet
from httpbin_python_sdk.paths.user_agent.get import UserAgentGet
from httpbin_python_sdk.apis.tags.request_inspection_api_raw import RequestInspectionApiRaw


class RequestInspectionApi(
    IncomingHeadersGet,
    IpAddressGet,
    UserAgentGet,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: RequestInspectionApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = RequestInspectionApiRaw(api_client)
