# coding: utf-8

"""
    httpbin.org

    A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>

    The version of the OpenAPI document: 0.9.2
    Contact: me@kennethreitz.org
    Created by: https://kennethreitz.org
"""

from httpbin_python_sdk.paths.brotli.get import BrotliGetData
from httpbin_python_sdk.paths.deflate.get import DeflateDataGet
from httpbin_python_sdk.paths.deny.get import DeniedPageGet
from httpbin_python_sdk.paths.robots_txt.get import GetRobotsRules
from httpbin_python_sdk.paths.gzip.get import GzipDataGet
from httpbin_python_sdk.paths.html.get import SimpleHtmlGet
from httpbin_python_sdk.paths.json.get import SimpleJsonGet
from httpbin_python_sdk.paths.xml.get import SimpleXmlGet
from httpbin_python_sdk.paths.encoding_utf8.get import Utf8BodyGet
from httpbin_python_sdk.apis.tags.response_formats_api_raw import ResponseFormatsApiRaw


class ResponseFormatsApi(
    BrotliGetData,
    DeflateDataGet,
    DeniedPageGet,
    GetRobotsRules,
    GzipDataGet,
    SimpleHtmlGet,
    SimpleJsonGet,
    SimpleXmlGet,
    Utf8BodyGet,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ResponseFormatsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ResponseFormatsApiRaw(api_client)
