# coding: utf-8

"""
    httpbin.org

    A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>

    The version of the OpenAPI document: 0.9.2
    Contact: me@kennethreitz.org
    Created by: https://kennethreitz.org
"""

from httpbin_python_sdk.paths.cache_value.get import CacheControlSetRaw
from httpbin_python_sdk.paths.response_headers.post import GetResponseHeadersRaw
from httpbin_python_sdk.paths.cache.get import NotModifiedGetRaw
from httpbin_python_sdk.paths.response_headers.get import QueryHeadersGetRaw
from httpbin_python_sdk.paths.etag_etag.get import ResourceInspectionGetRaw


class ResponseInspectionApiRaw(
    CacheControlSetRaw,
    GetResponseHeadersRaw,
    NotModifiedGetRaw,
    QueryHeadersGetRaw,
    ResourceInspectionGetRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
