# coding: utf-8

"""
    httpbin.org

    A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>

    The version of the OpenAPI document: 0.9.2
    Contact: me@kennethreitz.org
    Created by: https://kennethreitz.org
"""

from httpbin_python_sdk.paths.brotli.get import BrotliGetDataRaw
from httpbin_python_sdk.paths.deflate.get import DeflateDataGetRaw
from httpbin_python_sdk.paths.deny.get import DeniedPageGetRaw
from httpbin_python_sdk.paths.robots_txt.get import GetRobotsRulesRaw
from httpbin_python_sdk.paths.gzip.get import GzipDataGetRaw
from httpbin_python_sdk.paths.html.get import SimpleHtmlGetRaw
from httpbin_python_sdk.paths.json.get import SimpleJsonGetRaw
from httpbin_python_sdk.paths.xml.get import SimpleXmlGetRaw
from httpbin_python_sdk.paths.encoding_utf8.get import Utf8BodyGetRaw


class ResponseFormatsApiRaw(
    BrotliGetDataRaw,
    DeflateDataGetRaw,
    DeniedPageGetRaw,
    GetRobotsRulesRaw,
    GzipDataGetRaw,
    SimpleHtmlGetRaw,
    SimpleJsonGetRaw,
    SimpleXmlGetRaw,
    Utf8BodyGetRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
