# coding: utf-8

"""
    httpbin.org

    A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>

    The version of the OpenAPI document: 0.9.2
    Contact: me@kennethreitz.org
    Created by: https://kennethreitz.org
"""

from httpbin_python_sdk.paths.status_codes.get import ReturnRandomCodeRaw
from httpbin_python_sdk.paths.status_codes.put import ReturnRandomCode0Raw
from httpbin_python_sdk.paths.status_codes.post import ReturnRandomCode1Raw
from httpbin_python_sdk.paths.status_codes.delete import ReturnRandomCode2Raw
from httpbin_python_sdk.paths.status_codes.patch import ReturnRandomCode3Raw
from httpbin_python_sdk.paths.status_codes.trace import ReturnRandomCode4Raw


class StatusCodesApiRaw(
    ReturnRandomCodeRaw,
    ReturnRandomCode0Raw,
    ReturnRandomCode1Raw,
    ReturnRandomCode2Raw,
    ReturnRandomCode3Raw,
    ReturnRandomCode4Raw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
