# coding: utf-8

"""
    httpbin.org

    A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>

    The version of the OpenAPI document: 0.9.2
    Contact: me@kennethreitz.org
    Created by: https://kennethreitz.org
"""

from httpbin_python_sdk.paths.status_codes.get import ReturnRandomCode
from httpbin_python_sdk.paths.status_codes.put import ReturnRandomCode0
from httpbin_python_sdk.paths.status_codes.post import ReturnRandomCode1
from httpbin_python_sdk.paths.status_codes.delete import ReturnRandomCode2
from httpbin_python_sdk.paths.status_codes.patch import ReturnRandomCode3
from httpbin_python_sdk.paths.status_codes.trace import ReturnRandomCode4
from httpbin_python_sdk.apis.tags.status_codes_api_raw import StatusCodesApiRaw


class StatusCodesApi(
    ReturnRandomCode,
    ReturnRandomCode0,
    ReturnRandomCode1,
    ReturnRandomCode2,
    ReturnRandomCode3,
    ReturnRandomCode4,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: StatusCodesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = StatusCodesApiRaw(api_client)
